pipeline_version: "v1.0"
process_name: "slvr_historical_nse_load"
run_id: "1"
process_id: "job_slvr_historical_nse_load"

# Logging paths
app_log_file: "./logs/local_job_slvr_nse_historical_app.log"
spark_log_file: "./logs/local_job_slvr_nse_historical_app_spark.log"

input_tables:
  brnz_nse_historical: "local.market_lakehouse.bronze_nse_historical_prices_raw"

output_table: "local.market_lakehouse.slvr_nse_historical_prices_till_29_oct_2023"

load_type: "full"

